n_prompt: "bad quality, worse quality"
inpaint_prompt: "a red flower blooming in the river"
relight_prompt: "a red flower blooming in the river, nature lighting"

video_path: "input_animatediff/bloom.mp4"
bg_source: "TOP"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.4
gamma: 0.5
num_step: 50
text_guide_scale: 4
seed: 8776