n_prompt: "bad quality, worse quality"
inpaint_prompt: "A tiny camera on a tray, cyberpunk"
relight_prompt: "A tiny camera on a tray, cyberpunk, neon light"

video_path: "input_animatediff/camera.mp4"
bg_source: "LEFT"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.4
gamma: 0.5
num_step: 50
text_guide_scale: 3
seed: 1333