n_prompt: "bad quality, worse quality"
inpaint_prompt: "a car driving on the beach, sunset over sea"
relight_prompt: "a car driving on the beach, sunset over sea, left light, shadow"

video_path: "input_animatediff/car.mp4"
bg_source: "LEFT"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 50
text_guide_scale: 2
seed: 2409