n_prompt: "bad quality, worse quality"
inpaint_prompt: "A coin on the desk"
relight_prompt: "A coin on the desk, natural lighting"

video_path: "input_animatediff/coin.mp4"
bg_source: "TOP"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.4
gamma: 0.5
num_step: 80
text_guide_scale: 2
seed: 4013