n_prompt: "bad quality, worse quality"
inpaint_prompt: "A man in a bar, left yellow and right purple neon lights"
relight_prompt: "A man in a bar, left yellow and right purple neon lights, hard light"

video_path: "input_animatediff/man3.mp4"
bg_source: "RIGHT"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 50
text_guide_scale: 4
seed: 9528