n_prompt: "bad quality, worse quality"
inpaint_prompt: "A man in the classroom"
relight_prompt: "A man in the classroom, sunshine from the window"

video_path: "input_animatediff/man3.mp4"
bg_source: "RIGHT"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 50
text_guide_scale: 3
seed: 3931