n_prompt: "bad quality, worse quality"
inpaint_prompt: "a wolf stands in an alley, detailed face, neon, Wong Kar-wai, warm"
relight_prompt: "a wolf stands in an alley, detailed face, neon, Wong Kar-wai, warm, right light"

video_path: "input_animatediff/wolf2.mp4"
bg_source: "RIGHT"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 50
text_guide_scale: 5
seed: 2172