n_prompt: "bad quality, worse quality"
vdm_prompt: "a man walking in the factory"
relight_prompt: "a man walking in the factory, red and blue neon light"
video_path: "input_wan/man.mp4"
bg_source: "LEFT"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
num_frames: 49
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42