n_prompt: "bad quality, worse quality"
relight_prompt: "a bear walking on the rock, nature lighting, key light"
video_path: "input_animatediff/bear.mp4"
bg_source: "TOP"  ## NONE, LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 512
height: 512
strength: 0.5
gamma: 0.5
num_step: 25
text_guide_scale: 2
seed: 42